
language: c

notifications:
 - email: true

before_install:
 - sudo apt-get install libnl-3-dev libnl-genl-3-dev
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update
 - sudo apt-get install gcc-7 g++-7 -y
 - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
 - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
 - gcc --version
 - g++ --version


script:
 # Compilation
 - ./autogen.sh
 - ./configure
 - make
